// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipesDataAccess.Data;

#nullable disable

namespace RecipesDataAccess.Migrations
{
    [DbContext(typeof(RecipesDBContext))]
    partial class RecipesDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CategoryRecipes", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CategoryId", "RecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("CategoryRecipes", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            RecipeId = 1
                        },
                        new
                        {
                            CategoryId = 2,
                            RecipeId = 2
                        },
                        new
                        {
                            CategoryId = 3,
                            RecipeId = 3
                        },
                        new
                        {
                            CategoryId = 5,
                            RecipeId = 4
                        },
                        new
                        {
                            CategoryId = 4,
                            RecipeId = 5
                        },
                        new
                        {
                            CategoryId = 6,
                            RecipeId = 6
                        },
                        new
                        {
                            CategoryId = 7,
                            RecipeId = 7
                        },
                        new
                        {
                            CategoryId = 8,
                            RecipeId = 8
                        },
                        new
                        {
                            CategoryId = 9,
                            RecipeId = 9
                        },
                        new
                        {
                            CategoryId = 10,
                            RecipeId = 10
                        });
                });

            modelBuilder.Entity("Favorites", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("Favorites", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RecipeId = 2
                        },
                        new
                        {
                            UserId = 2,
                            RecipeId = 1
                        },
                        new
                        {
                            UserId = 3,
                            RecipeId = 5
                        },
                        new
                        {
                            UserId = 4,
                            RecipeId = 4
                        },
                        new
                        {
                            UserId = 5,
                            RecipeId = 3
                        },
                        new
                        {
                            UserId = 6,
                            RecipeId = 6
                        },
                        new
                        {
                            UserId = 7,
                            RecipeId = 7
                        },
                        new
                        {
                            UserId = 8,
                            RecipeId = 8
                        },
                        new
                        {
                            UserId = 9,
                            RecipeId = 9
                        },
                        new
                        {
                            UserId = 10,
                            RecipeId = 10
                        });
                });

            modelBuilder.Entity("RecipeIngredients", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RecipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("RecipeIngredients", (string)null);

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 1
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 2
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 7
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 6
                        },
                        new
                        {
                            RecipeId = 5,
                            IngredientId = 4
                        },
                        new
                        {
                            RecipeId = 6,
                            IngredientId = 7
                        },
                        new
                        {
                            RecipeId = 7,
                            IngredientId = 9
                        },
                        new
                        {
                            RecipeId = 8,
                            IngredientId = 8
                        },
                        new
                        {
                            RecipeId = 9,
                            IngredientId = 6
                        },
                        new
                        {
                            RecipeId = 10,
                            IngredientId = 10
                        });
                });

            modelBuilder.Entity("RecipeSteps", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StepId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RecipeId", "StepId");

                    b.HasIndex("StepId");

                    b.ToTable("RecipeSteps", (string)null);

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            StepId = 1
                        },
                        new
                        {
                            RecipeId = 2,
                            StepId = 2
                        },
                        new
                        {
                            RecipeId = 3,
                            StepId = 3
                        },
                        new
                        {
                            RecipeId = 4,
                            StepId = 4
                        },
                        new
                        {
                            RecipeId = 5,
                            StepId = 5
                        },
                        new
                        {
                            RecipeId = 6,
                            StepId = 6
                        },
                        new
                        {
                            RecipeId = 7,
                            StepId = 7
                        },
                        new
                        {
                            RecipeId = 8,
                            StepId = 8
                        },
                        new
                        {
                            RecipeId = 9,
                            StepId = 9
                        },
                        new
                        {
                            RecipeId = 10,
                            StepId = 10
                        });
                });

            modelBuilder.Entity("RecipesDataAccess.Models.CategoryDM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("CategoryId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("ValidFrom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ValidTo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Italian",
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(6959),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Name = "Indian",
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(6969),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mexican",
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(6973),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Name = "French",
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(6977),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Name = "Japanese",
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(6980),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Name = "Chinese",
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(6984),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Name = "Mediterranean",
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(6988),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Name = "American",
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(6992),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Name = "Thai",
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(6996),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Name = "Spanish",
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(7000),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("RecipesDataAccess.Models.IngredientDM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("IngredientId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Quantity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValidFrom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ValidTo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Spaghetti",
                            Quantity = "200g",
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(7052),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Name = "Chicken",
                            Quantity = "500g",
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(7061),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tomatoes",
                            Quantity = "3 pcs",
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(7066),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Name = "Garlic",
                            Quantity = "2 cloves",
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(7071),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Name = "Olive Oil",
                            Quantity = "50ml",
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(7075),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Name = "Rice",
                            Quantity = "250g",
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(7080),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Name = "Beef",
                            Quantity = "400g",
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(7084),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Name = "Potatoes",
                            Quantity = "3 pcs",
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(7089),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Name = "Cheese",
                            Quantity = "100g",
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(7093),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Name = "Basil",
                            Quantity = "10 leaves",
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(7097),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("RecipesDataAccess.Models.RecipeDM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("RecipeId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ValidFrom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ValidTo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("UserId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Classic Italian pasta.",
                            Name = "Spaghetti Carbonara",
                            UserId = 1,
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(7245),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Aromatic curry with chicken.",
                            Name = "Chicken Curry",
                            UserId = 2,
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(7257),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Description = "Mexican street food.",
                            Name = "Beef Tacos",
                            UserId = 3,
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(7262),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Description = "Japanese delicacy.",
                            Name = "Sushi Roll",
                            UserId = 4,
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(7267),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Description = "Rich and savory.",
                            Name = "French Onion Soup",
                            UserId = 5,
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(7273),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Description = "Chinese classic.",
                            Name = "Sweet and Sour Pork",
                            UserId = 6,
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(7279),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Description = "Fresh Mediterranean salad.",
                            Name = "Greek Salad",
                            UserId = 7,
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(7294),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Description = "American comfort food.",
                            Name = "Burger Deluxe",
                            UserId = 8,
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(7299),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Description = "Thai stir-fried noodles.",
                            Name = "Pad Thai",
                            UserId = 9,
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(7304),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Description = "Spanish rice dish.",
                            Name = "Paella",
                            UserId = 10,
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(7309),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("RecipesDataAccess.Models.StepDM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("StepId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("ValidFrom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ValidTo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Steps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Boil pasta until al dente.",
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(7153),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cook chicken with onions and garlic.",
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(7160),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Name = "Chop vegetables finely.",
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(7164),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Name = "Simmer sauce for 20 minutes.",
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(7168),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Name = "Preheat oven to 180°C.",
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(7172),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Name = "Grill beef until medium rare.",
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(7175),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Name = "Steam rice until fluffy.",
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(7179),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Name = "Mash potatoes with butter.",
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(7183),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Name = "Mix salad dressing.",
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(7188),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Name = "Serve hot with garnish.",
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(7192),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("RecipesDataAccess.Models.UserDM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("UserId");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("ValidFrom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "anna@example.com",
                            PasswordHash = "hash1",
                            UserName = "ChefAnna",
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(6401),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Email = "masoud@example.com",
                            PasswordHash = "hash2",
                            UserName = "ChefSam",
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(6464),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Email = "luca@example.com",
                            PasswordHash = "hash3",
                            UserName = "ChefLuca",
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(6481),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Email = "maria@example.com",
                            PasswordHash = "hash4",
                            UserName = "ChefMaria",
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(6487),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Email = "tom@example.com",
                            PasswordHash = "hash5",
                            UserName = "ChefTom",
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(6492),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Email = "sara@example.com",
                            PasswordHash = "hash6",
                            UserName = "ChefSara",
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(6497),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Email = "ali@example.com",
                            PasswordHash = "hash7",
                            UserName = "ChefAli",
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(6502),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Email = "emma@example.com",
                            PasswordHash = "hash8",
                            UserName = "ChefEmma",
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(6507),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Email = "john@example.com",
                            PasswordHash = "hash9",
                            UserName = "ChefJohn",
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(6511),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Email = "sophia@example.com",
                            PasswordHash = "hash10",
                            UserName = "ChefSophia",
                            ValidFrom = new DateTime(2026, 5, 27, 12, 5, 30, 828, DateTimeKind.Local).AddTicks(6516),
                            ValidTo = new DateTime(2090, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CategoryRecipes", b =>
                {
                    b.HasOne("RecipesDataAccess.Models.CategoryDM", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipesDataAccess.Models.RecipeDM", null)
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Favorites", b =>
                {
                    b.HasOne("RecipesDataAccess.Models.RecipeDM", null)
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipesDataAccess.Models.UserDM", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RecipeIngredients", b =>
                {
                    b.HasOne("RecipesDataAccess.Models.IngredientDM", null)
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipesDataAccess.Models.RecipeDM", null)
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RecipeSteps", b =>
                {
                    b.HasOne("RecipesDataAccess.Models.RecipeDM", null)
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipesDataAccess.Models.StepDM", null)
                        .WithMany()
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RecipesDataAccess.Models.RecipeDM", b =>
                {
                    b.HasOne("RecipesDataAccess.Models.UserDM", "User")
                        .WithMany("Recipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecipesDataAccess.Models.UserDM", b =>
                {
                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
