// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

using System;
using System.Collections.Generic;
namespace RecipesDataAccess.Data;

public partial class RecipesDBContext : DbContext
{
    public RecipesDBContext(DbContextOptions<RecipesDBContext> options)
     : base(options)
    {
    
    }



    public DbSet<UserDM> Users { get; set; }
    public DbSet<RecipeDM> Recipes { get; set; }

    public DbSet<CategoryDM> Categories { get; set; }
    public DbSet<IngredientDM> Ingredients { get; set; }
    public DbSet<StepDM> Steps { get; set; }

    //public DbSet<FavoriteDM> Favorites { get; set; }

    // Junctions
    //public DbSet<RecipeIngredientDM> RecipeIngredients { get; set; }
    //public DbSet<FavoriteDM> Favorites { get; set; }
    //public DbSet<CategoryRecipeDM> CategoryRecipes { get; set; }



    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        

        base.OnModelCreating(modelBuilder);

        modelBuilder.Entity<UserDM>()
        .Property(u => u.Id)
        .HasColumnName("UserId");

        modelBuilder.Entity<CategoryDM>()
            .Property(c => c.Id)
            .HasColumnName("CategoryId");

        modelBuilder.Entity<StepDM>()
            .Property(s => s.Id)
            .HasColumnName("StepId");

        modelBuilder.Entity<RecipeDM>()
           .Property(r => r.Id)
           .HasColumnName("RecipeId");
        modelBuilder.Entity<IngredientDM>()
          .Property(i => i.Id)
          .HasColumnName("IngredientId");



        modelBuilder.Entity<RecipeDM>()
           .HasKey(r => r.Id);

        modelBuilder.Entity<UserDM>()
            .HasKey(u => u.Id);


        // User -> Recipe (1:N)


        modelBuilder.Entity<RecipeDM>()
            .HasOne(r => r.User)
            .WithMany(u => u.Recipes)
            .HasForeignKey(r => r.UserId);

        // Category key
        modelBuilder.Entity<CategoryDM>()
            .HasKey(c => c.Id);

        // Step key
        modelBuilder.Entity<StepDM>()
            .HasKey(s => s.Id);

        // Ingredient key
        modelBuilder.Entity<IngredientDM>()
            .HasKey(i => i.Id);

        // Recipe <-> Category (M:N via CategoryRecipes)
        modelBuilder.Entity<RecipeDM>()
            .HasMany(r => r.Categories)
            .WithMany(c => c.Recipes)
            .UsingEntity<Dictionary<string, object>>(
                "CategoryRecipes",
                j => j.HasOne<CategoryDM>().WithMany().HasForeignKey("CategoryId"),
                j => j.HasOne<RecipeDM>().WithMany().HasForeignKey("RecipeId"),
                j => j.HasKey("CategoryId", "RecipeId")
            );

        // Recipe <-> Step (M:N via RecipeSteps)
        modelBuilder.Entity<RecipeDM>()
            .HasMany(r => r.Steps)
            .WithMany(s => s.Recipes)
            .UsingEntity<Dictionary<string, object>>(
                "RecipeSteps",
                j => j.HasOne<StepDM>().WithMany().HasForeignKey("StepId"),
                j => j.HasOne<RecipeDM>().WithMany().HasForeignKey("RecipeId"),
                j => j.HasKey("RecipeId", "StepId")
            );

        // Recipe <-> Ingredient (M:N via RecipeIngredients)
        modelBuilder.Entity<RecipeDM>()
            .HasMany(r => r.Ingredients)
            .WithMany(i => i.Recipes)
            .UsingEntity<Dictionary<string, object>>(
                "RecipeIngredients",
                j => j.HasOne<IngredientDM>().WithMany().HasForeignKey("IngredientId"),
                j => j.HasOne<RecipeDM>().WithMany().HasForeignKey("RecipeId"),
                j => j.HasKey("RecipeId", "IngredientId")
            );


        // User <-> Recipe (M:N via Favorites)
        modelBuilder.Entity<UserDM>()
            .HasMany(u => u.FavoriteRecipes)
            .WithMany(r => r.FavoritedBy)
            .UsingEntity<Dictionary<string, object>>(
                "Favorites",
                j => j.HasOne<RecipeDM>().WithMany().HasForeignKey("RecipeId"),
                j => j.HasOne<UserDM>().WithMany().HasForeignKey("UserId"),
                j =>
                {
                    // both FKs  => PK
                    j.HasKey("UserId", "RecipeId");
                    j.ToTable("Favorites"); // “Stop guessing. Use this exact table name.”
                }
            );


        // Recipe ↔ Category
        modelBuilder.Entity<RecipeDM>()
            .HasMany(r => r.Categories)
            .WithMany(c => c.Recipes)
            .UsingEntity(j => j.ToTable("CategoryRecipes"));

        // Recipe ↔ Ingredient
        modelBuilder.Entity<RecipeDM>()
            .HasMany(r => r.Ingredients)
            .WithMany(i => i.Recipes)
            .UsingEntity(j => j.ToTable("RecipeIngredients"));

        // Recipe ↔ Step
        modelBuilder.Entity<RecipeDM>()
            .HasMany(r => r.Steps)
            .WithMany(s => s.Recipes)
            .UsingEntity(j => j.ToTable("RecipeSteps"));

        // User ↔ Recipe (Favorites)
        modelBuilder.Entity<UserDM>()
            .HasMany(u => u.FavoriteRecipes)
            .WithMany(r => r.FavoritedBy)
            .UsingEntity(j => j.ToTable("Favorites"));


        // Uniqueness of recipe names should be handled in application logic,
        // since we want to allow duplicates for expired recipes and keep history.
        modelBuilder.Entity<RecipeDM>()
         .HasIndex(r => r.Name);
            

        modelBuilder.Entity<RecipeDM>()
    .Property(r => r.Name)
    .IsRequired();

        modelBuilder.Entity<IngredientDM>()
          .HasIndex(r => r.Name)
            .IsUnique();

        modelBuilder.Entity<IngredientDM>()
    .Property(r => r.Name)
    .IsRequired();

        modelBuilder.Entity<CategoryDM>()
         .HasIndex(r => r.Name)
           .IsUnique();
        modelBuilder.Entity<CategoryDM>()
    .Property(r => r.Name)
    .IsRequired();

        modelBuilder.Entity<UserDM>()
         .HasIndex(r => r.UserName)
           .IsUnique();

        modelBuilder.Entity<UserDM>()
         .HasIndex(r => r.Email)
           .IsUnique();

        modelBuilder.Entity<StepDM>()
        .HasIndex(s => s.Name)
        .IsUnique();

        modelBuilder.Entity<StepDM>()
        .Property(r => r.Name).IsRequired();

        modelBuilder.Entity<IngredientDM>()
        .Property(c => c.ValidTo)
        .HasDefaultValue(new DateTime(2090, 1, 1, 0, 0, 0));

        modelBuilder.Entity<CategoryDM>()
        .Property(c => c.ValidTo)
        .HasDefaultValue(new DateTime(2090, 1, 1, 0, 0, 0));

        modelBuilder.Entity<RecipeDM>()
       .Property(c => c.ValidTo)
       .HasDefaultValue(new DateTime(2090, 1, 1, 0, 0, 0));

        modelBuilder.Entity<StepDM>()
        .Property(c => c.ValidTo)
        .HasDefaultValue(new DateTime(2090, 1, 1, 0, 0, 0));




        modelBuilder.Entity<CategoryDM>()
            .Property(c => c.Name)
            .UseCollation("NOCASE"); // case-insensitive comparison


        modelBuilder.Entity<IngredientDM>()
            .Property(c => c.Name)
            .UseCollation("NOCASE");


        modelBuilder.Entity<StepDM>()
            .Property(c => c.Name)
            .UseCollation("NOCASE");

        modelBuilder.Entity<RecipeDM>()
           .Property(c => c.Name)
           .UseCollation("NOCASE");


        modelBuilder.Entity<UserDM>()
            .Property(c => c.UserName)
            .UseCollation("NOCASE");

        modelBuilder.Entity<CategoryDM>()
        .Property(c => c.ValidFrom)
        .HasDefaultValueSql("CURRENT_TIMESTAMP");


        modelBuilder.Entity<IngredientDM>()
       .Property(c => c.ValidFrom)
       .HasDefaultValueSql("CURRENT_TIMESTAMP");
        modelBuilder.Entity<StepDM>()
       .Property(c => c.ValidFrom)
       .HasDefaultValueSql("CURRENT_TIMESTAMP");


        modelBuilder.Entity<RecipeDM>()
       .Property(c => c.ValidFrom)
       .HasDefaultValueSql("CURRENT_TIMESTAMP");


        modelBuilder.Entity<UserDM>()
       .Property(c => c.ValidFrom)
       .HasDefaultValueSql("CURRENT_TIMESTAMP");

        // Users
        modelBuilder.Entity<UserDM>().HasData(
            new UserDM { Id = 1, UserName = "ChefAnna", Email = "anna@example.com", PasswordHash = "hash1" },
            new UserDM { Id = 2, UserName = "ChefSam", Email = "masoud@example.com", PasswordHash = "hash2" },
            new UserDM { Id = 3, UserName = "ChefLuca", Email = "luca@example.com", PasswordHash = "hash3" },
            new UserDM { Id = 4, UserName = "ChefMaria", Email = "maria@example.com", PasswordHash = "hash4" },
            new UserDM { Id = 5, UserName = "ChefTom", Email = "tom@example.com", PasswordHash = "hash5" },
            new UserDM { Id = 6, UserName = "ChefSara", Email = "sara@example.com", PasswordHash = "hash6" },
            new UserDM { Id = 7, UserName = "ChefAli", Email = "ali@example.com", PasswordHash = "hash7" },
            new UserDM { Id = 8, UserName = "ChefEmma", Email = "emma@example.com", PasswordHash = "hash8" },
            new UserDM { Id = 9, UserName = "ChefJohn", Email = "john@example.com", PasswordHash = "hash9" },
            new UserDM { Id = 10, UserName = "ChefSophia", Email = "sophia@example.com", PasswordHash = "hash10" }
        );

        // Categories
        modelBuilder.Entity<CategoryDM>().HasData(
            new CategoryDM { Id = 1, Name = "Italian" },
            new CategoryDM { Id = 2, Name = "Indian" },
            new CategoryDM { Id = 3, Name = "Mexican" },
            new CategoryDM { Id = 4, Name = "French" },
            new CategoryDM { Id = 5, Name = "Japanese" },
            new CategoryDM { Id = 6, Name = "Chinese" },
            new CategoryDM { Id = 7, Name = "Mediterranean" },
            new CategoryDM { Id = 8, Name = "American" },
            new CategoryDM { Id = 9, Name = "Thai" },
            new CategoryDM { Id = 10, Name = "Spanish" }
        );

        // Ingredients
        modelBuilder.Entity<IngredientDM>().HasData(
            new IngredientDM { Id = 1, Name = "Spaghetti", Quantity = "200g" },
            new IngredientDM { Id = 2, Name = "Chicken", Quantity = "500g" },
            new IngredientDM { Id = 3, Name = "Tomatoes", Quantity = "3 pcs" },
            new IngredientDM { Id = 4, Name = "Garlic", Quantity = "2 cloves" },
            new IngredientDM { Id = 5, Name = "Olive Oil", Quantity = "50ml" },
            new IngredientDM { Id = 6, Name = "Rice", Quantity = "250g" },
            new IngredientDM { Id = 7, Name = "Beef", Quantity = "400g" },
            new IngredientDM { Id = 8, Name = "Potatoes", Quantity = "3 pcs" },
            new IngredientDM { Id = 9, Name = "Cheese", Quantity = "100g" },
            new IngredientDM { Id = 10, Name = "Basil", Quantity = "10 leaves" }
        );

        // Steps
        modelBuilder.Entity<StepDM>().HasData(
            new StepDM { Id = 1, Name = "Boil pasta until al dente." },
            new StepDM { Id = 2, Name = "Cook chicken with onions and garlic." },
            new StepDM { Id = 3, Name = "Chop vegetables finely." },
            new StepDM { Id = 4, Name = "Simmer sauce for 20 minutes." },
            new StepDM { Id = 5, Name = "Preheat oven to 180°C." },
            new StepDM { Id = 6, Name = "Grill beef until medium rare." },
            new StepDM { Id = 7, Name = "Steam rice until fluffy." },
            new StepDM { Id = 8, Name = "Mash potatoes with butter." },
            new StepDM { Id = 9, Name = "Mix salad dressing." },
            new StepDM { Id = 10, Name = "Serve hot with garnish." }
        );

        // Recipes
        modelBuilder.Entity<RecipeDM>().HasData(
            new RecipeDM { Id = 1, Name = "Spaghetti Carbonara", Description = "Classic Italian pasta.", UserId = 1 },
            new RecipeDM { Id = 2, Name = "Chicken Curry", Description = "Aromatic curry with chicken.", UserId = 2 },
            new RecipeDM { Id = 3, Name = "Beef Tacos", Description = "Mexican street food.", UserId = 3 },
            new RecipeDM { Id = 4, Name = "Sushi Roll", Description = "Japanese delicacy.", UserId = 4 },
            new RecipeDM { Id = 5, Name = "French Onion Soup", Description = "Rich and savory.", UserId = 5 },
            new RecipeDM { Id = 6, Name = "Sweet and Sour Pork", Description = "Chinese classic.", UserId = 6 },
            new RecipeDM { Id = 7, Name = "Greek Salad", Description = "Fresh Mediterranean salad.", UserId = 7 },
            new RecipeDM { Id = 8, Name = "Burger Deluxe", Description = "American comfort food.", UserId = 8 },
            new RecipeDM { Id = 9, Name = "Pad Thai", Description = "Thai stir-fried noodles.", UserId = 9 },
            new RecipeDM { Id = 10, Name = "Paella", Description = "Spanish rice dish.", UserId = 10 }
        );


        modelBuilder.Entity("CategoryRecipes").HasData(
            new { RecipeId = 1, CategoryId = 1 },
            new { RecipeId = 2, CategoryId = 2 },
            new { RecipeId = 3, CategoryId = 3 },
            new { RecipeId = 4, CategoryId = 5 },
            new { RecipeId = 5, CategoryId = 4 },
            new { RecipeId = 6, CategoryId = 6 },
            new { RecipeId = 7, CategoryId = 7 },
            new { RecipeId = 8, CategoryId = 8 },
            new { RecipeId = 9, CategoryId = 9 },
            new { RecipeId = 10, CategoryId = 10 }
        );

        modelBuilder.Entity("RecipeIngredients").HasData(
            new { RecipeId = 1, IngredientId = 1 },
            new { RecipeId = 2, IngredientId = 2 },
            new { RecipeId = 3, IngredientId = 7 },
            new { RecipeId = 4, IngredientId = 6 },
            new { RecipeId = 5, IngredientId = 4 },
            new { RecipeId = 6, IngredientId = 7 },
            new { RecipeId = 7, IngredientId = 9 },
            new { RecipeId = 8, IngredientId = 8 },
            new { RecipeId = 9, IngredientId = 6 },
            new { RecipeId = 10, IngredientId = 10 }
        );

        modelBuilder.Entity("RecipeSteps").HasData(
            new { RecipeId = 1, StepId = 1 },
            new { RecipeId = 2, StepId = 2 },
            new { RecipeId = 3, StepId = 3 },
            new { RecipeId = 4, StepId = 4 },
            new { RecipeId = 5, StepId = 5 },
            new { RecipeId = 6, StepId = 6 },
            new { RecipeId = 7, StepId = 7 },
            new { RecipeId = 8, StepId = 8 },
            new { RecipeId = 9, StepId = 9 },
            new { RecipeId = 10, StepId = 10 }
        );

        modelBuilder.Entity("Favorites").HasData(
    new { UserId = 1, RecipeId = 2 }, // ChefAnna favorites Chicken Curry
    new { UserId = 2, RecipeId = 1 }, // ChefSam favorites Spaghetti Carbonara
    new { UserId = 3, RecipeId = 5 }, // ChefLuca favorites French Onion Soup
    new { UserId = 4, RecipeId = 4 }, // ChefMaria favorites Sushi Roll
    new { UserId = 5, RecipeId = 3 }, // ChefTom favorites Beef Tacos
    new { UserId = 6, RecipeId = 6 }, // ChefSara favorites Sweet and Sour Pork
    new { UserId = 7, RecipeId = 7 }, // ChefAli favorites Greek Salad
    new { UserId = 8, RecipeId = 8 }, // ChefEmma favorites Burger Deluxe
    new { UserId = 9, RecipeId = 9 }, // ChefJohn favorites Pad Thai
    new { UserId = 10, RecipeId = 10 } // ChefSophia favorites Paella
);
    }        
}